### ISSUE TITLE
make it customizable

### ISSUE THREAD

**Issue by ogezue** [monoqlo/ExpandingMenu#1]
Hi - first of all: Great project - it would really help me in my project.

It would be great if you could make it more customizable for the end users. E.g. I would like to have a transparent bottomViewColor and I would like to change the color of the menu titles. 

What do you think?

**Comment by monoqlo** [comment]
It sounds good.

As a first step, I added some properties. please take a look.
edb2d6fcaeb6b6cccb9a9f2a1f02f519e72a9c10
7afe699a31025387fec696aac5fce29d5c04bd60

You can change title text, text color, bottom view alpha, whether the tapped action fires when title are tapped.

**Comment by ogezue** [comment]
That's great. I switched over to my autolayout version I posted in another issue, because my app will support portrait and landscape. It would be great if you can support autolayout too (with all the fancy animations you have now)
