### ISSUE TITLE
Reduce the text size of the items.

### ISSUE THREAD

**Issue by LiveRock** [monoqlo/ExpandingMenu#11]
How to do it?

**Comment by LiveRock** [comment]
ok, I did it with
button.titleLabel!.font = UIFont(name: "myfont" , size: 14)

How about reducing the distance between the text and the item button?

**Comment by monoqlo** [comment]
@LiveRock I currently set 8.0px to the margin. 

I'll make it possible to set any value by public property if you want.
Please wait a while.

**Comment by monoqlo** [comment]
I added the property. 96f7879d422183e98b53b2eafc886cd8fa908e24
