### ISSUE TITLE
Cocoapods install issue

### ISSUE THREAD

**Issue by muratyasarr** [monoqlo/ExpandingMenu#12]
Hello, I have an issue while installing the pod. When I try to install the cocoapods, I get the following error:

```
[!] /usr/bin/git clone https://github.com/monoqlo/ExpandingMenu.git /var/folders/ls/g04xq0yn4nj89q29xynn9h2w0000gn/T/d20160621-11755-4i7chp --template= --single-branch --depth 1 --branch 0.1.3

Cloning into '/var/folders/ls/g04xq0yn4nj89q29xynn9h2w0000gn/T/d20160621-11755-4i7chp'...
fatal: unable to access 'https://github.com/monoqlo/ExpandingMenu.git/': Could not resolve host: github.com
```

Do you have any idea how to solve this issue?

Thank you.

Best wishes, 
Murat Yaşar

**Comment by monoqlo** [comment]
@muratyasarr Umm... maybe, it doesn't depend on my pod.

Could you install the other library by cocoapods?

**Comment by muratyasarr** [comment]
@monoqlo interestingly the issue disappeared for some reason but I couldn't catch why it resolved. Thank you very much.

Bests,
Murat
