### ISSUE TITLE
Pod version 0.3 is not installing

### ISSUE THREAD

**Issue by kseniya-hydric** [monoqlo/ExpandingMenu#16]
Hi, I'm trying to add pod 'ExpandingMenu', '~> 0.3' to my project but getting an error:

None of your spec sources contain a spec satisfying the dependency: `ExpandingMenu (~> 0.3)`.

When I remove the version number, it always installs 0.2. My project is in Swift 3 so 0.2 asks me to convert. I'm guessing something is not up to date with your pod spec? 

Thank you!

**Comment by monoqlo** [comment]
I fixed it with CocoaPods 1.1.0.rc.1!, but it causes warning when installing. 

I haven't known what is best to adapt podspec for Xcode 8/Swift 3.
Please let me know if you know.

**Comment by monoqlo** [comment]
I added .swift-version file from 0.3.1.
