### ISSUE TITLE
Can't run carthage update build

### ISSUE THREAD

**Issue by Cunqi** [monoqlo/ExpandingMenu#17]
carthage update --platform iOS --verbose
**\* Fetching ExpandingMenu
**\* Checking out ExpandingMenu at "0.3.1"
**\* Skipped building ExpandingMenu due to the error:
Dependency "ExpandingMenu" has no shared framework schemes for any of the platforms: iOS

**Comment by YSDC** [comment]
same for me, any idea why??

**Comment by monoqlo** [comment]
I fixed this issue 346d2ec53a328e89fd1289a025c6341558d748ee
You can install this library ver 0.4.0 by Carthage.
