### ISSUE TITLE
Typo In README.md Example Code

### ISSUE THREAD

**Issue by dingwilson** [monoqlo/ExpandingMenu#22]
# Typo In README.md Example Code
There is a small error in the example code in the README.md under "Customize" -> "ExpandingMenuButton".

`exclusiveOr` should be `symmetricDifference` in

`menuButton.enabledExpandingAnimations = AnimationOptions.All.exclusiveOr(.MenuItemRotation)`

Thank you for writing this library! 👍

**Comment by monoqlo** [comment]
Thanks for your report.
I fixed it! 520ec236a57966dc6f34972c7032863024bcb810
