### ISSUE TITLE
Xcode 8.3: 'M_PI' is deprecated WARNING

### ISSUE THREAD

**Issue by aguila9** [monoqlo/ExpandingMenu#23]
Hi there,
I just update to Xcode 8.3. I'm getting 8 'M_PI' is deprecated warnings.
Is anyone else getting this warnings?
Thanks,

**Comment by alapergola** [comment]
just replace M_PI with: 

> Double.pi

 and it will work.

Et voilà

**Comment by aguila9** [comment]
I'm using cocoapod. When I try to modify a file in the framework it says the file is locked. How do I modify the file?
Thanks,

**Comment by alapergola** [comment]
top right side of the current open page into xcode you'll see a little locker icon. Click on there and simply 'unlock' the file from editing.

**Comment by monoqlo** [comment]
Fixed.
https://github.com/monoqlo/ExpandingMenu/pull/25
