### ISSUE TITLE
Can I stop rotation of subitems?

### ISSUE THREAD

**Issue by Ying1986** [monoqlo/ExpandingMenu#4]
@monoqlo 
Thank you for your help.

I have received your message for fix background color.

I need one to use it.
Can you add option to stop ration of sub menus? (+ button is ok).

**Comment by monoqlo** [comment]
Added animation options to ver 0.1.3. 

You can remove rotation animation.
```Swift
menuButton.enabledExpandingAnimations = AnimationOptions.Default.exclusiveOr(.MenuItemRotation)
menuButton.enabledFoldingAnimations = AnimationOptions.Default.exclusiveOr(.MenuItemRotation)
```
