### ISSUE TITLE
Typo in description

### ISSUE THREAD

**Issue by lfarah** [monoqlo/ExpandingMenu#8]
Should be ```ExpandingMenu``` instead of *ExpandingMene*
<img width="432" alt="screen shot 2016-04-06 at 10 16 08 pm" src="https://cloud.githubusercontent.com/assets/6511079/14341278/315aa406-fc45-11e5-858e-deb33811f581.png">

**Comment by monoqlo** [comment]
Thank you for reporting. I fixed it.
