### ISSUE TITLE
Make it appear down instead of up

### ISSUE THREAD

**Issue by LiveRock** [monoqlo/ExpandingMenu#9]
Hi

Possible to change the appearance of the sub button items downwards instead of upwards?

That is, the main button is at the top and when clicked, buttons appear in one column from top..

**Comment by monoqlo** [comment]
Please try this code.

```swift
menuButton.expandingDirection = .Bottom
```

**Comment by LiveRock** [comment]
Thanks, it works! 
How about reducing the distance between the items button. as I may have up to 12 items and they may go out of screen. Many Thanks!

**Comment by LiveRock** [comment]
I got it.

set the margin?

menuButtonMainCat.menuItemMargin = -30

**Comment by LiveRock** [comment]
Are you able to make the item buttons schrollable so I can get more buttons and they wont go out of the screen. Many thanks!
